webpack-contrib/webpack-hot-middleware

- client.js
RE: #11 - in addition to 94da926, fixes hot loadng in IE11
> require eventsource-polyfill from client.js

- middleware.js
To fix: https://github.com/glenjamin/webpack-hot-middleware/issues/18
> Fix for when webpack plugin builds multiple bundles.

- middleware.js
Reverts glenjamin/webpack-hot-middleware#19
> Revert "Fix for when webpack plugin builds multiple bundles."

- README.md
- example/README.md
- example/extra.js
- example/index-multientry.html
- example/package.json
- example/server.js
- example/webpack.config.multientry.js
This adds a working example of a multi entry points webpack config for the hot reload middleware.
Let me know if this is not your preferred approach of adding a second example. I didnt want to duplicate all of the configs/server.js, etc. since the only thing that is really different is the webpack config.
> Multiple entry points example

- README.md
Add brief snippet for use with koa. #20
> Documentation: Use with koa

- package.json
> move ansi-to-html-umd to dependencies from devDependencies

- process-update.js
Supports both webpack 1's callback and webpack 2's promise function signatures for `module.hot.apply()`. Related to #70.
> Handling webpack 2 promise version of module.hot.apply

- README.md
Hi!
Here's little fix for koa example.
Proof http://koajs.com/#context
> Fix koa api example

- client.js
This small changes fixes infinite duplication of previous warnings.
> add cache for warnings

- README.md
- client.js
- test/client-test.js
fixes #143 
Our use case at Yahoo is basically having 1 server serving mobile & desktop, which necessitates the usage of multi-compiler.
cc @glenjamin @Swatinem
> support multi-compiler mode

- .npmignore
Ref: https://github.com/glenjamin/webpack-hot-middleware/issues/195
> Chore: reduce package size.

- README.md
> use NoEmitOnErrorsPlugin

- process-update.js
Make HMR print warnings and errors when update fails
> Better debugging

- README.md
[koa-webpack](https://www.npmjs.com/package/koa-webpack) provides functionality for Koa@2 and above. Please consider adding this to the README 😄
> Update README with koa-webpack info

- test/middleware-test.js
Just a typo fix
None
Just a typo fix
> typos in middleware test comments

- middleware.js
- test/middleware-test.js
See #230 and #176
None, new api
> Add close method

- middleware.js
HMR stopped working with our project starting with v2.23.0.  I did some digging and found that this one particular stats.toJson option, `all: false`, is causing the issue and removing it fixes HMR for our use case.  Unless there is a specific reason for keeping it, I'd love to see it removed incase it is breaking other projects as well.
n/a
package.json (shortened to relevant bits)
```
"devDependencies": {
"@babel/cli": "^7.1.2",
"@babel/core": "^7.1.2",
"@babel/plugin-proposal-class-properties": "^7.1.0",
"@babel/plugin-proposal-decorators": "^7.1.2",
"@babel/plugin-proposal-object-rest-spread": "^7.0.0",
"@babel/preset-env": "^7.1.0",
"@babel/preset-react": "^7.0.0",
"@babel/preset-typescript": "^7.1.0",
"babel-loader": "^8.0.4",
"babel-preset-modern-browsers": …
```
> Add `cache: true` from stats.toJson options to fix HMR in certain setups

- process-update.js
Trim some trailing whitespace in file.
> Trim trailing whitespace

- .gitignore
- package-lock.json
- package.json
`npm audit` was reporting potential problems with some of our dependencies.
This PR is just a result of running `npm audit fix`.
/CC @evilebottnawi @glenjamin
> Audit dependencies

- .eslintrc
- client-overlay.js
- client.js
- helpers.js
- middleware.js
- package-lock.json
- package.json
- process-update.js
- test/client-test.js
- test/helpers-test.js
- test/middleware-test.js
- test/realistic-test.js
This PR integrates and runs prettier. Same rules of others webpack-contrib projects were applied.
/CC @evilebottnawi @glenjamin
> Integrate pretty on the project.

- example/README.md
Add description about how to correctly use codes under examples folder.
- [x ] **typo fix**
I got a error when I'm trying to setup an experimental environment under example folder.
After create issue, I got understand I missed one step. Just add some description about my foolish mistakes in case there is someone meet the same error.
None
None
> Resolve webpack-contrib/webpack-hot-middleware#353

- client-overlay.js
Fix for typo for ansi color option https://github.com/webpack-contrib/webpack-hot-middleware/issues/262
None
> Fix ansi colors

- README.md
- example/client.js
- example/package-lock.json
- example/package.json
- example/server.js
- example/webpack.config.js
- example/webpack.config.multientry.js
- middleware.js
- package-lock.json
- package.json
- test/realistic-test.js
fixes https://github.com/webpack-contrib/webpack-hot-middleware/pull/397/
No
No
> fix: compatibility with webpack v5

- README.md
fix: updated 'entry array' to 'main array of entry object' and gave example of implementation
to help clarify issue found at https://stackoverflow.com/questions/66322997/webpack-hot-middleware-setup-with-single-entry-point
> docs(readme): update install instructions

- middleware.js
[stats.toJson](https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/middleware.js#L190) is a heavy method, and is called for every incremental build.
I made a webpack build performance profiling, and found that `stats.toJson` from `webpack-hot-middleware` takes around 50ms work - while complete incremental build for small change is cost around 200-250ms fo CPU work.
After trying to change [statsOptions](https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/middleware.js#L117), I found that `cached: true` option is the slowest, and with disabled `cached: false` full `stats.toJson` call cost around 10ms - five times faster.
Looks like we don't need this option for most projects, but for backward compatibility I just add one parameter to …
> perf: option to exclude cached from stats

- middleware.js
Better stats options configuration, based on https://github.com/webpack-contrib/webpack-hot-middleware/pull/441#issuecomment-1867913183 comment
> refactor: statsOptions parameter
