- client.js
Hi Glen, thank you for this middleware.
This PR simply checks for existence of body before appending the `problemOverlay` div. This is currently throwing an error in our app that does some custom `document.body` replacement.
Would appreciate a merge + npm publish when you get the chance, cheers.
> Only append overlay to document when body exists.

- middleware.js
Ran into this while trying to load `http://localhost:3000/__webpack_hmr` from another domain.
> Add header to allow XHR hot-loading

- client.js
I was banging my head against this issue for a couple of days: my build has a couple of warnings but with the Webpack Dev Server it would update the code just fine, but webpack-hot-middleware wouldn't. Turns out you're not updating the build when there's a warning. This change just brings the webpack-hot-middleware behaviour inline with the server. 
Hopefully it'll save some people from going through my journey again!
> Don't fail update on warnings

- client.js
Bug Example:
```
> __resourceQuery = '?path=http://localhost:3001/__webpack_hmr';
> qs.parse(__resourceQuery)
{ '?path': 'http://localhost:3001/__webpack_hmr' }
```
Just removed the `?` at the beginning, now path is overridden.
> Path Option was broken

- README.md
Looks like there was a little typo in the documentation for the `quiet` option for the client.
> Fix client option typo in README

- README.md
This PR closes #33 by providing instructions in the README for using multiple entry points in your webpack config.
I'll work on an example which I'll submit as a separate PR.
> Add multiple entry points to README

- client.js
This is a followup to #15. 
While having warnings (e.g. `console.log`) in the build, the error overlay is not cleared after fixing the broken build.
Doing a full page refresh after every eslint mistake gets annoying quite quickly :)
> Don't skip clearing the screen if build only had warnings

- example/webpack.config.js
I am putting this here as it seems the best place for now.
In hindsight it seems obvious but I did scratch my head to make it work with the component being loaded from a Django application and thus residing on a different port. I could not figure out how to make the calls to hmr tp localhost:8000 go to the nodejs server :)
> Add comment on using full urls in config

- process-update.js
The warning misleadingly suggested a reload was happening. Might be even better to warn that a reload is necessary, but not occurring.
NOTE: I winged this in Github web editor without testing, because I'm lazy and optimistic. Think it should work, but caveat emptor.
> only warn about reload if actually reloading

- client-overlay.js
1. Don’t use `pre` tag because it can be styled by site’s style sheet.
2. Add padding to make it more readable.
For example with Bootstrap it looks like this:
And with this pull request like this:
> Improve styles

- package.json
npm v3 tries to dedupe the dependencies by default, and keeping dependencies up-to-date helps better deduplication.
> Update strip-ansi and istanbul

- middleware.js
I'm debugging a Webpack server in Chrome DevTools (see [devtool](https://github.com/Jam3/devtool)) and logging is broken without this PR, since the context is not correct.
> fix console.log in Chrome DevTools

- client.js
- middleware.js
- test/middleware-test.js
Webpack allows "multi-compiler" execution that changes what the stats result looks like.  Instead of a flat object, it adds a children property with an array of stats objects.
https://github.com/webpack/webpack/tree/master/examples/multi-compiler
e.g.
```javascript
{
children: [
{time: ...},
{time: ...},
]
}
```
> fix stats reporting on multicompiler builds

- client.js
Somewhat related to #9 : this method addition allows the user to customize the overlay behavior. This allows implementing the overlay using arbitrary libraries without coupling it with `webpack-hot-middleware`.
Example usage:
``` js
var hotClient = require('webpack-hot-middleware/client')
hotClient.useCustomOverlay({
showProblems: function (lines) {
// ...
},
clear: function () {
// ...
}
})
```
Different overlay implementations can be shipped as npm modules:
``` js
var hotClient = require('webpack-hot-middleware/client')
var myOverlay = require('my-fancy-hot-middleware-overlay')
hotClient.useCustomOverlay(myOverlay)
```
> Add ability to use custom overlay implementation

- client-overlay.js
- client.js
- package.json
This PR integrates [Dan's suggestions](https://github.com/glenjamin/webpack-hot-middleware/issues/9#issuecomment-190036073) for a nicer error overlay (#9)
I've forked [rburns/ansi-to-html](https://github.com/rburns/ansi-to-html) as [ansi-to-html-umd](https://github.com/rossipedia/ansi-to-html-umd), and use webpack and webpack/json-loader to build a UMD version, which this pull request uses.
> Integrate @gaearon's nicer overlay ( #9 )

- client-overlay.js
- client.js
- package.json
- Using [ansi-html](https://www.npmjs.com/package/ansi-html) instead of ansi-to-html-umd, which gives us the ability to customize the color output instead of hard-coded colors; (also avoid having to do the umd wrap)
- Adjusted color scheme, fonts, spacing, and added problem type labels. Also added slight opacity to background so that it's more obvious to the user that the current app state is being preserved.
- Moved the ANSI -> HTML conversion logic into `client-overlay.js` instead of `client.js`. This way custom overlay implementations receive raw ANSI strings instead of pre-converted HTML so that they have more flexibility in how to display the messages.
> Even better overlay styling

- client-overlay.js
REMs are units relative to a viewport's font size, so if it's set to a small one (like 8px) overlay would have lines jumping over each other
> Remvoing REM use from "lineHeight" property

- process-update.js
Small change that supports both webpack 1's callback and webpack 2's promise for `module.hot.check()`. Fixes #70.
> Support for webpack 2 module.hot.check promise

- client-overlay.js
- client.js
Currently with a multi-entry setup, every entry's hot client will inject a copy of the overlay on to the page. When a compilation error is thrown, it will be sent to all these overlays regardless of which entry chunk it was associated with, therefore there will be multiple overlays open at the same time.
This PR simply ensures there will be only one overlay injected at a time.
> overlay should be injected into the page only once

- README.md
- client.js
[This is my use case](https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/58702f67a96f1c1b9fecda562e9e39476d162931/webpack/customPublicPath.js), I customize `__webpack_public_path__` in the program (not in webpack config), but this module cannot use it as prefix of `path`.
> Add config for use webpack publicPath as prefix of path

- client.js
- test/client-test.js
Usage:
client.subscribeAll(function(message) {
console.log(message.action);
});
Only accepts one handler and will overwrite any previously existing
handlers. Addresses #111
> Adds a subscribeAll() method to the client to handle any events

- middleware.js
Tested with `npm test` and in a local project running HTTP/2 via node-spdy.
Have not tested with vanilla HTTP or HTTPS.
> Remove Transfer-Encoding: chunked header from middleware (fixes #114)

- client-overlay.js
This will fixes the issue where the parent element (body or html) have a different direction value like `rtl`.
> Make client overlay direction left-to-right

- client.js
- middleware.js
- test/client-test.js
- test/middleware-test.js
Currently, if you refresh the client whilst the compilation is in an error state you don't get any feedback (and if using the NoErrorsPlugin you actually get a working app; albeit using the last working bundle) -- you need to check the terminal window to be sure this hasn't happened.
This PR aims to solve the problem by publishing the 'built' event based on the last known compilation stats as soon as a client is registered with the middleware meaning the client script will show the overlay if appropriate.
> Show error overlay even after browser refresh

- middleware.js
This will fix the issue: https://github.com/storybooks/react-storybook/issues/543
We do this by using `stats.toJson({ errorDetails: false })` as [mentioned](https://github.com/storybooks/react-storybook/issues/543#issuecomment-258881932) by @SpaceK33z.
I tested this with Storybook and the above issue is gone with this fix.
> Fix duplicate errors on the client overlay

- client-overlay.js
Adds an id to the client overlay, which allows it to be customized with external CSS.
Also, set a text-align property on it.
> Allow client overlay styles to be customized

- client.js
Warning messages were barely readable in console with a dark theme.
#999933 is a color that is more adaptable to both light and dark consoles.
> Changes warning color for dark console themes

- middleware.js
When the server with webpack-hot-middleware is behind Nginx proxy, it's not flushing messages immediately.
There are two ways to do so - set up special Nginx rule for this endpoint to proxy it a different way (/__webpack_hmr) or set up a header on server side which is treated as special by Nginx.
Webpack-hot-middleware is only for development purposes. I think that it's worth to add this header for people who i.e. have Docker setup for development machines behind Nginx (what is pretty common I think).
> Tell Nginx to proxy event stream messages from webpack-hot-middleware

- README.md
https://webpack.github.io/docs/ has now been deprecated. 
> webpack v1 is deprecated. We encourage all developers to upgrade to webpack 2.
This PR updates links to webpack docs to the new and up to date webpack 2 docs.
> Update deprecated webpack docs links to webpack 2

- example/webpack.config.multientry.js
Webpack 2.0 fixed a typo in the OccurrenceOrderPluing (was Occurence).
https://github.com/webpack/webpack/issues/1964
> Update OccurrenceOrderPlugin spelling

- README.md
As the OccurenceOrderPlugin has a note about webpack 1, I figured we should include a note about NoEmitOnErrorsPlugin for consistency.
> Add note about NoErrorsPlugin in webpack 1

- README.md
- client.js
Add function to allow options to be changed without having to use resourceQuery by using the function setOptions.
Unfortunately its not possible to modify the queryString used when importing webpack-hot-middleware with dynamic values, as import statements don't/shouldn't contain any logic.
This change is to allow Next.js to move closer to fully supporting assetPrefixing. The PR using these changes is here: https://github.com/zeit/next.js/pull/2901
> Allow easier option configuration

- README.md
- client-overlay.js
- client.js
- example/index.html
- example/webpack.config.multientry.js
Addresses #262 minus the [parser comment](https://github.com/glenjamin/webpack-hot-middleware/issues/262#issuecomment-344595300). Not sure how to easily get that stack trace to show up in the example. Seems like you'd need a more complex setup than that of the example folder.
In addition to allowing for customization of the ansi colors via `ansiColors`, this also lets you customize the inline styles of the overlay div via `overlayStyles`.
Other related tickets #256 #261
> Custom Client Colors & Styles

- example/index.html
I'd been trying to get HMR working with the package and decided to clone the repo so I can see how the example works. Kept getting 404's when it was calling client.js. Looked into the webpack config and noticed it was creating a file called bundle.js.
> fixed call to bundle file in example

- middleware.js
- test/middleware-test.js
Following https://github.com/glenjamin/webpack-hot-middleware/pull/260.
As suggested https://github.com/webpack/webpack/issues/6633#issuecomment-369715848, we rather iterate each compiler and register the 'compile' hook when getting a MultiCompiler instance than register the 'invalid' hook.
> Replace 'compile' with 'invalid' hook.

- .circleci/config.yml
- Removes `setup_remote_docker`
- Compares the next & latest dist-tag for Webpack & executes the Canary tests suite ( or doesn't )
> ci(circle): Pick up latest config from defaults

- middleware.js
- test/middleware-test.js
webpack-hot-middleware must to support HTTP/2 out of the box.
Nope.
It's impossible to cover with tests HTTP/2 mode right now because Express HTTP/2 support is in progress: https://github.com/expressjs/express/pull/3390
> Support HTTP/2

- middleware.js
- test/middleware-test.js
This is related to a PR I opened [here](https://github.com/60frames/webpack-hot-server-middleware/pull/82). I'm currently upgrading a project to Webpack 4 and I'm not sure if the `toJson()` call got heavier but it's a pretty expensive call and probably always has been somewhat. Enough so that my muti-compiler setup can run out of memory when it's called without explicitly setting the options. This updates the the `toJson()` call to only request the stats necessary needed for the publish call. 
This also falls back to logging the compilation name when there's no `stat.name` available.
No breaking changes.
> Performance improvement

- process-update.js
Getting more informative output about reloaded modules especially when code splitting takes place.
https://github.com/webpack-contrib/webpack-hot-middleware/issues/306
> Using a fallback moduleId if it cannot be found in the moduleMap

- client-overlay.js
This PR contains is to fix #359.
The style of the client overlay is slightly change for better readability.
This PR doesn't introduce breaking changes
Here are some before after screenshot of the client overlay.
**WARNING**
_before_
_after_
**ERROR**
_before_
_after_
> improved client overlay style

- README.md
- client-overlay.js
- package-lock.json
- package.json
This is a fix for the vulnerability reported in [CVE-2021-23424][CVE] by
replacing the ansi-html dependency with a fork of the project that has
the [suggested fix][ansi-html-fix] and resolves [#412][412]
[CVE]: https://nvd.nist.gov/vuln/detail/CVE-2021-23424
[ansi-html-fix]: https://github.com/Tjatse/ansi-html/issues/19
[412]: https://github.com/webpack-contrib/webpack-hot-middleware/issues/412
> fix: replace ansi-html with ansi-html-community to fix vulnerability

- client.js
- package-lock.json
- package.json
The querystring API is deprecated
changing the querystring API for the URLSearchParams API could bring breaking changes as the querystring API remove trailing characters from the params and URLSearchParams don't, but in the webpack hot middleware case, this should not be a breaking change, also the URLSearchParams API is not available in node 0.4 and below, that might be a little issue
> feat: replace querystring with urlsearchparams

- .circleci/config.yml
Webpack 4 and Node 17+ don't mix - see https://github.com/webpack/webpack/issues/14532 for details
For now we'll just only test against node 16.
none
> Only test against LTS for now, as webpack 4 doesn't work on node 18

- .circleci/config.yml
- middleware.js
- test/fixtures/multi-compiler/.gitignore
- test/middleware-test.js
- test/realistic-test.js
This PR aims to address an issue I think is related to #390, 
Details of my system setup;
- Operating System: Mac
- Node Version: v16.18.0
- NPM Version: 8.19.2
- Yarn Version: 1.22.17
- webpack Version: ^5.7.3
- ${package} Version: 2.25.2
I had a similar issue on further investigation, I realized that the problem happens because the shape of stats object returned in Webpack 5 differs from that of Webpack 4. [See here](https://github.com/webpack/webpack/blob/main/lib/MultiCompiler.js#L97). 
This PR checks the returned stats object for the `stats` property on the returned `statsResult` which also present on multicomplier stats results generated from Webpack, the returned stats is handled as such if this is the case, from there on everything works like it should.
> feat: improve logic for handling multicomplier stats result to accomodate webpack5

- client.js
Occasionally I need to test on legacy browsers. `webpack-hot-middleware` has pretty good support for older browsers but I've spotted a case where it could broaden its support. Replacing `Object.fromEntries` with `reduce` should bring back support for Chrome 49-72, Safari 10.1-12.0 and Firefox 44-62 (based upon comparing caniuse tables for [`Object.fromEntries`](https://caniuse.com/mdn-javascript_builtins_object_fromentries) and [`UrlSearchParams`](https://caniuse.com/urlsearchparams)), assuming that "browsers that support `UrlSearchParams`" is the bottom boundary.
> Replace usage of `Object.fromEntries` with `reduce`

- middleware.js
Solves 'moduleName' and 'loc' converted to string `undefined` if not present in middleware's error formatter (for webpack 5 errors)
No breaking changes introduced
[Related issue ticket](https://github.com/webpack-contrib/webpack-hot-middleware/issues/446)
> Add fallbacks to `moduleName` and `loc` webpack 5 error fields if not present in middleware's error formatter
